apiVersion: apps/v1
kind: Deployment
metadata:
  name: universe-simulator-gateway-app-deployment
  namespace: universe-simulator
  labels:
    app: universe-simulator
    service: universe-simulator-gateway-app
spec:
  template:
    metadata:
      labels:
        app: universe-simulator
        service: universe-simulator-gateway-app
    spec:
      containers:
        - name: universe-simulator-gateway-app
          image: universesimulator/gateway:90
          envFrom:
            - configMapRef:
                name: universe-simulator-gateway-app-config-map
          readinessProbe:
            periodSeconds: 2
            httpGet:
              port: 8443
              path: /actuator/health/readiness
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 2
            httpGet:
              port: 8443
              path: /actuator/health/liveness
  selector:
    matchLabels:
      app: universe-simulator
      service: universe-simulator-gateway-app
  replicas: 1
