apiVersion: apps/v1
kind: Deployment
metadata:
  name: universe-simulator-gateway-app-deployment
  namespace: universe-simulator
  labels:
    app: universe-simulator
    service: universe-simulator-gateway-app
spec:
  template:
    metadata:
      labels:
        app: universe-simulator
        service: universe-simulator-gateway-app
    spec:
      containers:
        - name: universe-simulator-gateway-app
          image: universesimulator/gateway:57
          envFrom:
            - configMapRef:
                name: universe-simulator-gateway-app-config-map
          volumeMounts:
            - name: cert-volume
              mountPath: /home/cnb/universe-simulator/universe-simulator.p12
              readOnly: true
      volumes:
        - name: cert-volume
          hostPath:
            path: /Users/nkvaratskhelia/universe-simulator/universe-simulator.p12
  selector:
    matchLabels:
      app: universe-simulator
      service: universe-simulator-gateway-app
  replicas: 1
