apiVersion: v1
kind: Service
metadata:
  name: universe-simulator-gateway-app-service
  labels:
    app: universe-simulator-gateway-app
spec:
  type: NodePort
  ports:
    - port: 8443
      nodePort: 30000
  selector:
    app: universe-simulator-gateway-app
